# Generated by Django 4.0.1 on 2022-02-06 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('unique', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('birth', models.DateField(verbose_name='생년월일')),
                ('phonenumber', models.CharField(max_length=11, unique=True, verbose_name='휴대폰 번호')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='평점')),
                ('joindate', models.DateField(default=datetime.datetime.now, editable=False)),
                ('lastLogin', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
