# Generated by Django 4.0.1 on 2022-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_joindate_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(default='', verbose_name='위치'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(default='', max_length=5, verbose_name='우편번호'),
        ),
    ]
