# Generated by Django 4.0.1 on 2022-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('unique', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25, verbose_name='제목')),
                ('category', models.IntegerField(verbose_name='카테고리')),
                ('content', models.TextField(verbose_name='상품설명')),
                ('imageCnt', models.IntegerField(verbose_name='이미지 수')),
                ('image1', models.TextField(verbose_name='이미지1')),
                ('image2', models.TextField(verbose_name='이미지2')),
                ('image3', models.TextField(verbose_name='이미지3')),
                ('image4', models.TextField(verbose_name='이미지4')),
                ('image5', models.TextField(verbose_name='이미지5')),
                ('image6', models.TextField(verbose_name='이미지6')),
                ('image7', models.TextField(verbose_name='이미지7')),
                ('image8', models.TextField(verbose_name='이미지8')),
                ('location', models.CharField(max_length=255, verbose_name='위치')),
            ],
        ),
    ]
