# Generated by Django 4.0.1 on 2022-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_delete_itemmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imageCnt',
            new_name='cntImg',
        ),
        migrations.AddField(
            model_name='item',
            name='postcode',
            field=models.CharField(default='', max_length=5, verbose_name='우편번호'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='item',
            name='pricePerHour',
            field=models.BooleanField(default=True, verbose_name='시간당 가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='위치'),
        ),
    ]
